from .base import env

FROM_EMAIL = env("FROM_EMAIL")
EMAIL_BACKEND = "django_ses.SESBackend"

AWS_SES_REGION_NAME = env("AWS_SES_REGION_NAME")
AWS_SES_REGION_ENDPOINT = env("AWS_SES_REGION_ENDPOINT")

DEFAULT_FROM_EMAIL = SERVER_EMAIL = FROM_EMAIL
